# Generated by Django 4.2.7 on 2023-11-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.basemodel')),
                ('lesson_quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
            bases=('course.basemodel',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.basemodel')),
                ('question_text', models.CharField(max_length=245)),
                ('img_question', models.FileField(blank=True, null=True, upload_to='')),
                ('question_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            bases=('course.basemodel',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.basemodel')),
                ('choice_text', models.CharField(max_length=245)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('choice_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            bases=('course.basemodel',),
        ),
    ]
