# Generated by Django 4.2.7 on 2023-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('cover_image', models.FileField(upload_to='')),
                ('duration', models.TimeField()),
                ('category', models.CharField(choices=[(1, 'web dev'), (2, 'accounting'), (3, 'digital marketing'), (4, 'Interior Design')], max_length=2)),
                ('lang', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('FR', 'French')], default='AR', max_length=2)),
            ],
        ),
    ]
