# Generated by Django 4.2.7 on 2023-11-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('userextension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.userextension')),
                ('courses', models.ManyToManyField(to='main.course')),
            ],
            bases=('main.userextension',),
        ),
    ]
