# Generated by Django 4.2.7 on 2023-11-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('WD', 'web dev'), ('AC', 'accounting'), ('DM', 'digital marketing'), ('ID', 'Interior Design')], max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, to='main.course'),
        ),
    ]
