# Generated by Django 4.2.7 on 2023-11-24 11:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_category_alter_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='username',
            field=models.CharField(default='deleted_user', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userextension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.userextension')),
                ('registered_courses', models.ManyToManyField(to='main.course')),
            ],
            bases=('main.userextension',),
        ),
    ]
