# Generated by Django 4.2.7 on 2023-11-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userextension_created_at_userextension_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
