# Generated by Django 4.2.7 on 2023-11-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
    ]
